exclude: azure-pipelines.yml
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.0
    hooks:
      - id: uv-lock
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1 # Replace by any tag/version: https://github.com/astral-sh/ruff-pre-commit/tags
    hooks:
      - id: ruff-check
        args: [--fix]
        files: ^(src/bo4e|generate_or_validate_json_schemas\.py)
      - id: ruff-format
