# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"
  jobs:
    pre_build:
      - python -m pip install -e .
      # This ensures that before trying to build the documentation, the package will have information about the
      # version tag. This is necessary for the documentation to build the links correctly.
      - python -c "import bo4e; print(bo4e.__gh_version__)"
      - TARGET_VERSION=$(python -c \'import bo4e;print(bo4e.__gh_version__)\')
      - echo $TARGET_VERSION
      - echo "The version of the package is $TARGET_VERSION"
      - echo $(python -c "import bo4e; print(bo4e.__gh_version__)")
      - python generate_or_validate_json_schemas.py --mode generate --target-version $TARGET_VERSION
      # https://github.com/readthedocs/readthedocs.org/issues/9397#issuecomment-1472056462

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
    - requirements: dev_requirements/requirements-json_schemas.txt
    - requirements: requirements.txt
