"""
This module makes it easier to import a business object.
For example: `from bo4e.com import Adresse`
"""

from .adresse import Adresse
from .angebotsposition import Angebotsposition
from .angebotsteil import Angebotsteil
from .angebotsvariante import Angebotsvariante
from .aufabschlag import AufAbschlag
from .aufabschlagproort import AufAbschlagProOrt
from .aufabschlagregional import AufAbschlagRegional
from .aufabschlagstaffelproort import AufAbschlagstaffelProOrt
from .ausschreibungsdetail import Ausschreibungsdetail
from .ausschreibungslos import Ausschreibungslos
from .betrag import Betrag
from .dienstleistung import Dienstleistung
from .energieherkunft import Energieherkunft
from .externereferenz import ExterneReferenz
from .fremdkostenblock import Fremdkostenblock
from .fremdkostenposition import Fremdkostenposition
from .geokoordinaten import Geokoordinaten
from .geraet import Geraet
from .geraeteeigenschaften import Geraeteeigenschaften
from .hardware import Hardware
from .katasteradresse import Katasteradresse
from .kostenblock import Kostenblock
from .kostenposition import Kostenposition
from .kriteriumwert import KriteriumWert
from .marktgebietinfo import MarktgebietInfo
from .menge import Menge
from .messlokationszuordnung import Messlokationszuordnung
from .positionsaufabschlag import PositionsAufAbschlag
from .preis import Preis
from .preisgarantie import Preisgarantie
from .preisposition import Preisposition
from .preisstaffel import Preisstaffel
from .rechnungsposition import Rechnungsposition
from .regionalegueltigkeit import RegionaleGueltigkeit
from .regionalepreisgarantie import RegionalePreisgarantie
from .regionalepreisstaffel import RegionalePreisstaffel
from .regionaleraufabschlag import RegionalerAufAbschlag
from .regionaletarifpreisposition import RegionaleTarifpreisposition
from .regionskriterium import Regionskriterium
from .rufnummer import Rufnummer
from .sigmoidparameter import Sigmoidparameter
from .standorteigenschaftengas import StandorteigenschaftenGas
from .standorteigenschaftenstrom import StandorteigenschaftenStrom
from .steuerbetrag import Steuerbetrag
from .tagesvektor import Tagesvektor
from .tarifberechnungsparameter import Tarifberechnungsparameter
from .tarifeinschraenkung import Tarifeinschraenkung
from .tarifpreis import Tarifpreis
from .tarifpreisposition import Tarifpreisposition
from .tarifpreispositionproort import TarifpreispositionProOrt
from .tarifpreisstaffelproort import TarifpreisstaffelProOrt
from .unterschrift import Unterschrift
from .verbrauch import Verbrauch
from .vertragskonditionen import Vertragskonditionen
from .vertragsteil import Vertragsteil
from .zaehlwerk import Zaehlwerk
from .zeitintervall import Zeitintervall
from .zeitraum import Zeitraum
from .zeitreihenwert import Zeitreihenwert
from .zeitreihenwertkompakt import Zeitreihenwertkompakt
from .zustaendigkeit import Zustaendigkeit
