"""Contains Enums for Abweichungsgrund."""
from bo4e.enum.strenum import StrEnum


class Abweichungsgrund(StrEnum):
    """Gibt einen Abweichungsgrund bei Ablehung einer COMDIS an. (REMADV SG7 AJT 4465)"""

    PREIS_RECHENREGEL_FALSCH = "PREIS_RECHENREGEL_FALSCH"  #: PREIS_RECHENREGEL_FALSCH, 5
    FALSCHER_ABRECHNUNGSZEITRAUM = "FALSCHER_ABRECHNUNGSZEITRAUM"  #: FALSCHER_ABRECHNUNGSZEITRAUM, 9
    UNBEKANNTE_MARKTLOKATION_MESSLOKATION = "UNBEKANNTE_MARKTLOKATION_MESSLOKATION"
    """UNBEKANNTE_MARKTLOKATION_MESSLOKATION, 14."""
    SONSTIGER_ABWEICHUNGSGRUND = "SONSTIGER_ABWEICHUNGSGRUND"  #: SONSTIGER_ABWEICHUNGSGRUND, 28
    DOPPELTE_RECHNUNG = "DOPPELTE_RECHNUNG"  #: DOPPELTE_RECHNUNG, 53
    ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN = "ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN"
    """ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN, Z01."""
    ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE = "ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE"
    """ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE, Z02."""
    BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH = "BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH"
    "BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH, Z03."
    VORAUSBEZAHLTER_BETRAG_FALSCH = "VORAUSBEZAHLTER_BETRAG_FALSCH"  #: VORAUSBEZAHLTER_BETRAG_FALSCH, Z04
    ARTIKEL_NICHT_VEREINBART = "ARTIKEL_NICHT_VEREINBART"  #: ARTIKEL_NICHT_VEREINBART, Z06
    NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN = "NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN"
    """NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN, Z07."""
    RECHNUNGSNUMMER_BEREITS_ERHALTEN = "RECHNUNGSNUMMER_BEREITS_ERHALTEN"  #: RECHNUNGSNUMMER_BEREITS_ERHALTEN, Z08
    NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH = "NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH"
    """NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH, Z10."""
    ZEITLICHE_MENGENANGABE_FEHLERHAFT = "ZEITLICHE_MENGENANGABE_FEHLERHAFT"  #: ZEITLICHE_MENGENANGABE_FEHLERHAFT, Z33
    FALSCHER_BILANZIERUNGSBEGINN = "FALSCHER_BILANZIERUNGSBEGINN"  #: FALSCHER_BILANZIERUNGSBEGINN, Z35
    FALSCHES_NETZNUTZUNGSENDE = "FALSCHES_NETZNUTZUNGSENDE"  #: FALSCHES_NETZNUTZUNGSENDE, Z36
    BILANZIERTE_MENGE_FEHLT = "BILANZIERTE_MENGE_FEHLT"  #: BILANZIERTE_MENGE_FEHLT, Z37
    BILANZIERTE_MENGE_FALSCH = "BILANZIERTE_MENGE_FALSCH"  #: BILANZIERTE_MENGE_FALSCH, Z38
    NETZNUTZUNGSABRECHNUNG_FEHLT = "NETZNUTZUNGSABRECHNUNG_FEHLT"  #: NETZNUTZUNGSABRECHNUNG_FEHLT, Z39
    REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT = "REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT"
    """REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT, Z40."""
    ALLOKATIONSLISTE_FEHLT = "ALLOKATIONSLISTE_FEHLT"  #: ALLOKATIONSLISTE_FEHLT, Z41
    MEHR_MINDERMENGE_FALSCH = "MEHR_MINDERMENGE_FALSCH"  #: MEHR_MINDERMENGE_FALSCH, Z42
    UNGUELTIGES_RECHNUNGSDATUM = "UNGUELTIGES_RECHNUNGSDATUM"  #: UNGUELTIGES_RECHNUNGSDATUM, Z43
    ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT = "ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT"
    "ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT, Z44."
    RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS = "RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS"  #: RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS, Z45
    ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN = "ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN"
    """ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN, Z52."""
    RECHNUNGSABWICKLUNG_NICHT_VEREINBART = "RECHNUNGSABWICKLUNG_NICHT_VEREINBART"
    """RECHNUNGSABWICKLUNG_NICHT_VEREINBART, Z53."""
    COMDIS_WIRD_ABGELEHNT = "COMDIS_WIRD_ABGELEHNT"  #: COMDIS_WIRD_ABGELEHNT, Z63
