"""Contains Enums for Abweichungsgrund."""
from bo4e.enum.strenum import StrEnum


class Abweichungsgrund(StrEnum):
    """Gibt einen Abweichungsgrund bei Ablehung einer COMDIS an. (REMADV SG7 AJT 4465)"""

    #: PREIS_RECHENREGEL_FALSCH, 5
    PREIS_RECHENREGEL_FALSCH = "PREIS_RECHENREGEL_FALSCH"
    #: FALSCHER_ABRECHNUNGSZEITRAUM, 9
    FALSCHER_ABRECHNUNGSZEITRAUM = "FALSCHER_ABRECHNUNGSZEITRAUM"
    #: UNBEKANNTE_MARKTLOKATION_MESSLOKATION, 14
    UNBEKANNTE_MARKTLOKATION_MESSLOKATION = "UNBEKANNTE_MARKTLOKATION_MESSLOKATION"
    #: SONSTIGER_ABWEICHUNGSGRUND, 28
    SONSTIGER_ABWEICHUNGSGRUND = "SONSTIGER_ABWEICHUNGSGRUND"
    #: DOPPELTE_RECHNUNG, 53
    DOPPELTE_RECHNUNG = "DOPPELTE_RECHNUNG"
    #: ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN, Z01
    ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN = "ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN"
    #: ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE, Z02
    ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE = "ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE"
    #: BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH, Z03
    BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH = "BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH"
    #: VORAUSBEZAHLTER_BETRAG_FALSCH, Z04
    VORAUSBEZAHLTER_BETRAG_FALSCH = "VORAUSBEZAHLTER_BETRAG_FALSCH"
    #: ARTIKEL_NICHT_VEREINBART, Z06
    ARTIKEL_NICHT_VEREINBART = "ARTIKEL_NICHT_VEREINBART"
    #: NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN, Z07
    NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN = "NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN"
    #: RECHNUNGSNUMMER_BEREITS_ERHALTEN, Z08
    RECHNUNGSNUMMER_BEREITS_ERHALTEN = "RECHNUNGSNUMMER_BEREITS_ERHALTEN"
    #: NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH, Z10
    NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH = "NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH"
    #: ZEITLICHE_MENGENANGABE_FEHLERHAFT, Z33
    ZEITLICHE_MENGENANGABE_FEHLERHAFT = "ZEITLICHE_MENGENANGABE_FEHLERHAFT"
    #: FALSCHER_BILANZIERUNGSBEGINN, Z35
    FALSCHER_BILANZIERUNGSBEGINN = "FALSCHER_BILANZIERUNGSBEGINN"
    #: FALSCHES_NETZNUTZUNGSENDE, Z36
    FALSCHES_NETZNUTZUNGSENDE = "FALSCHES_NETZNUTZUNGSENDE"
    #: BILANZIERTE_MENGE_FEHLT, Z37
    BILANZIERTE_MENGE_FEHLT = "BILANZIERTE_MENGE_FEHLT"
    #: BILANZIERTE_MENGE_FALSCH, Z38
    BILANZIERTE_MENGE_FALSCH = "BILANZIERTE_MENGE_FALSCH"
    #: NETZNUTZUNGSABRECHNUNG_FEHLT, Z39
    NETZNUTZUNGSABRECHNUNG_FEHLT = "NETZNUTZUNGSABRECHNUNG_FEHLT"
    #: REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT, Z40
    REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT = "REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT"
    #: ALLOKATIONSLISTE_FEHLT, Z41
    ALLOKATIONSLISTE_FEHLT = "ALLOKATIONSLISTE_FEHLT"
    #: MEHR_MINDERMENGE_FALSCH, Z42
    MEHR_MINDERMENGE_FALSCH = "MEHR_MINDERMENGE_FALSCH"
    #: UNGUELTIGES_RECHNUNGSDATUM, Z43
    UNGUELTIGES_RECHNUNGSDATUM = "UNGUELTIGES_RECHNUNGSDATUM"
    #: ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT, Z44
    ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT = "ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT"
    #: RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS, Z45
    RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS = (
        "RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS"
    )
    #: ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN, Z52
    ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN = "ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN"
    #: RECHNUNGSABWICKLUNG_NICHT_VEREINBART, Z53
    RECHNUNGSABWICKLUNG_NICHT_VEREINBART = "RECHNUNGSABWICKLUNG_NICHT_VEREINBART"
    #: COMDIS_WIRD_ABGELEHNT, Z63
    COMDIS_WIRD_ABGELEHNT = "COMDIS_WIRD_ABGELEHNT"
