"""
Auflistung sämtlicher existierender Geschäftsobjekte.
"""

from enum import Enum

_boTyp = {
    "MARKTLOKATION": "MARKTLOKATION",
    "MESSLOKATION": "MESSLOKATION",
    "GESCHAEFTSPARTNER": "GESCHAEFTSPARTNER",
    "ZAEHLER": "ZAEHLER",
    "ANSPRECHPARTNER": "ANSPRECHPARTNER",
    "ANGEBOT": "ANGEBOT",
    "MARKTTEILNEHMER": "MARKTTEILNEHMER",
    "ENERGIEMENGE": "ENERGIEMENGE",
    "KOSTEN": "KOSTEN",
    "AUSSCHREIBUNG": "AUSSCHREIUNG",
    "PREISBLATT": "PREISBLATT",
    "PREISBLATTNETZNUTZUNG": "PREISBLATTNETZNUTZUNG",
    "PREISBLATTMESSUNG": "PREISBLATTMESSUNG",
    "PREISBLATTDIENSTLEISTUNG": "PREISBLATTDIENSTLEISTUNG",
    "PREISBLATTUMLAGEN": "PREISBLATTUMLAGEN",
    "PREISBLATTKONZESSIONSABGABE": "PREISBLATTKONZESSIONSABGABE",
    "TARIFINFO": "TARIFINFO",
    "TARIFKOSTEN": "TARIFKOSTEN",
    "RECHNUNG": "RECHNUNG",
    "NETZNUTZUNGSRECHNUNG": "NETZNUTZUNGSRECHNUNG",
    "TARIFPREISBLATT": "TARIFPREISBLATT",
    "REGIONALTARIF": "REGIONALTARIF",
    "ZEITREIHE": "ZEITREIHE"
}
BoTyp = Enum("BoTyp", _boTyp)
