"""
List of possible Gebiettypen.
"""
from enum import Enum

_gebiettyp = {
    "REGELZONE": "REGELZONE",
    "MARKTGEBIET": "MARKTGEBIET",
    "BILANZIERUNGSGEBIET": "BILANZIERUNGSGEBIET",
    "VERTEILNETZ": "VERTEILNETZ",
    "TRANSPORTNETZ": "TRANSPORTNETZ",
    "REGIONALNETZ": "REGIONALNETZ",
    "AREALNETZ": "AREALNETZ",
    "GRUNDVERSORGUNGSGEBIET": "GRUNDVERSORGUNGSGEBIET",
    "VERSORGUNGSGEBIET": "VERSORGUNGSGEBIET",
}
Gebiettyp = Enum("Gebiettyp", _gebiettyp)
