from enum import Enum


class Gebietstyp(str, Enum):
    REGELZONE = "REGELZONE"
    MARKTGEBIET = "MARKTGEBIET"
    BILANZIERUNGSGEBIET = "BILANZIERUNGSGEBIET"
    VERTEILNETZ = "VERTEILNETZ"
    TRANSPORTNETZ = "TRANSPORTNETZ"
    REGIONALNETZ = "REGIONALNETZ"
    AREALNETZ = "AREALNETZ"
    GRUNDVERSORGUNGSGEBIET = "GRUNDVERSORGUNGSGEBIET"
    VERSORGUNGSGEBIET = "VERSORGUNGSGEBIET"
