"""
List of possible Gebiettypen.
"""
from enum import Enum

Gebiettyp = Enum(
    "Gebiettyp",
    {
        "REGELZONE": "REGELZONE",
        "MARKTGEBIET": "MARKTGEBIET",
        "BILANZIERUNGSGEBIET": "BILANZIERUNGSGEBIET",
        "VERTEILNETZ": "VERTEILNETZ",
        "TRANSPORTNETZ": "TRANSPORTNETZ",
        "REGIONALNETZ": "REGIONALNETZ",
        "AREALNETZ": "AREALNETZ",
        "GRUNDVERSORGUNGSGEBIET": "GRUNDVERSORGUNGSGEBIET",
        "VERSORGUNGSGEBIET": "VERSORGUNGSGEBIET",
    },
)
