# pylint: disable=missing-module-docstring
from bo4e.enum.strenum import StrEnum


class Voraussetzungen(StrEnum):
    """
    Voraussetzungen, die erfüllt sein müssen, damit dieser Tarif zur Anwendung kommen kann.
    """

    EINZUGSERMAECHTIGUNG  #: 3
    ZEITPUNKT  #: 3
    LIEFERANBINDUNG_EINE  #: 3
    LIEFERANBINDUNG_ALLE  #: 3
    GEWERBE  #: 3
    LASTPROFIL  #: 3
    ZAEHLERTYP_GROESSE  #: 3
    AUSSCHLUSS_GROSSVERBRAUCHER  #: 3
    NEUKUNDE  #: 3
    BESTIMMTE_VERTRAGSFORMALITAETEN  #: 3
    SELBSTABLESUNG  #: 3
    ONLINEVORAUSSETZUNG  #: 3
    MINDESTUMSATZ  #: 3
    ZUSATZPRODUKT  #: 3
    NEUKUNDE_MIT_VORAUSSETZUNGEN  #: 3
    DIREKTVERTRIEB  #: 3
    ANSCHLUSSART  #: 3
    ANSCHLUSSWERT  #: 3
    ALTER_KUNDENANLAGE  #: 3
    ANLAGEBESCHAFFENHEIT  #: 3
    BETRIEBSSTUNDENBEGRENZUNG  #: 3
    FREIGABEZEITEN  #: 3
    FAMILIENSTRUKTUR  #: 3
    MITGLIEDSCHAFT  #: 3
    STAATLICHE_FOERDERUNG  #: 3
    BESONDERE_VERBRAUCHSSTELLE  #: 3
    NIEDRIGENERGIE  #: 3
    ORTSTEILE_LIEFERGEBIET  #: 3
    WAERMEBEDARF_ERDGAS  #: 2
    MAX_ZAEHLER_LIEFERSTELLEN  #: 3
    LIEFERUNGSBESCHRAENKUNG_GASART  #: 2
    KOMBI_BONI  #: 3
    ALTVERTRAG  #: 3
    VORGESCHRIEBENE_ZUSATZANLAGE  #: 2
    MEHRERE_ZAEHLER_ABNAHMESTELLEN  #: 3
    BESTIMMTER_ABNAHMEFALL  #: 2
    ZUSATZMODALITAET  #: 3
    NACHWEIS_ZAHLUNGSFAEHIGKEIT  #: 3
    UMSTELLUNG_ENERGIEART  #: 3
