name: "Black"

on: [push]
jobs:
  black:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
        with:
          args: ". --check"
