name: "Linting"
on: [push]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  linting:
    name: Python Code Quality and Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest, windows-latest]
        linter-env: ["linting", "type_check", "dev"]
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.28"
          enable-cache: true
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv pip install tox tox-uv
      - name: Run ${{ matrix.linter-env }}
        run: |
          uv run tox -e ${{ matrix.linter-env }}
