name: Tests

on: [push]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          # Install a specific version of uv.
          version: "0.11.28"
          enable-cache: true
      - name: Install tox
        run: uv pip install tox tox-uv
      - name: Test with tox
        run: |
          uv run tox -e tests
