name: "Test Doc Creation (Sphinx)"
on: [pull_request]
jobs:
  docbuild:
    name: Check Docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run kroki with docker
        run: |
          docker compose up -d
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Check Docs
        run: |
          tox -e docs
